### ISSUE TITLE
Gracefully handle situations where image serializers are applied to incompatible arrays

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#113]
I have the following configuration.

Config.yml:
``` yml
# config.yml
trees:

  - path: "/"
    tree: files
    args:
      directory: "/home/dylan/data/beamlines/sequence_test"
      subdirectory_handler: tiled.readers.tiff_sequence:subdirectory_handler

uvicorn:
  host: 0.0.0.0
  port: 8000


```
And the contents of the sequence_test are:
.
├── sequence
│   └── 20211001_092045_toothpick_00055.tiff
└── test.txt

When I navigate to `http://0.0.0.0:8000/metadata/sequence` I get good output, including the "full link" `http://0.0.0.0:8000/array/full/sequence`

However, following that full link without slice parameters, the errors (returns 500) crashes with the following error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...trimmed...
  File "/home/dylan/miniconda3/envs/tiled/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/dylan/miniconda3/envs/tiled/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/dylan/miniconda3/envs/tiled/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/dylan/miniconda3/envs/tiled/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./tiled/server/router.py", line 325, in array_full
    array = reader.read(slice)
  File "./tiled/readers/tiff_sequence.py", line 84, in read
    image_axis, *the_rest = slice
```

Interestingly, I get the a similar result with the same error with hdf5 arrays. It really seems like slice is a required parameter. Should the router code check that slice has been sent and if not there, respond with a 400 rather than falling down into code a coming back with a 500 internal error?

**Comment by danielballan** [comment]
Closed by #154
