### ISSUE TITLE
Docker container requires writable /deploy directory for metrics

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#144]
An issue was found  running the stock Tiled container on the Spin infrastructure. The /deploy directory was mounted as read only, and the user was something other than root. Tiled fails to start.

I can reproduce locally using the instructions at https://blueskyproject.io/tiled/how-to/docker.html but changing the documentation to use ghcr image (which should probably be in the documentation).

```docker run --rm -p 8000:8000   --mount type=bind,source="$(pwd)/example_files",target=/deploy/example_files  --mount type=bind,source="$(pwd)/",target=/deploy   --env TILED_CONFIG=/deploy/config.yml ghcr.io/bluesky/tiled:main```

Tiled fails to start, because the it's requiring a writable /deploy directory for prometheus. The fix for spin was to make the `/deploy` mount writable, but that doesn't feel right. Not everyone will use prometheus and it is reasonable to make this directory read only. It feels like if you want to use prometheus, than sure, make it writeable. 

So what's the right fix? Make prometheus an option that you can turn on if you want?

```
[2021-12-16 23:30:38 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/tiled/server/app.py", line 33, in <module>
    from .metrics import capture_request_metrics
  File "/app/tiled/server/metrics.py", line 77, in <module>
    REQUEST_DURATION.labels(code=code, method="GET", endpoint=endpoint)
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 183, in labels
    self._metrics[labelvalues] = self.__class__(
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 548, in __init__
    super(Histogram, self).__init__(
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 131, in __init__
    self._metric_init()
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/metrics.py", line 576, in _metric_init
    self._sum = values.ValueClass(self._type, self._name, self._name + '_sum', self._labelnames, self._labelvalues)
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/values.py", line 70, in __init__
    self.__reset()
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/values.py", line 84, in __reset
    files[file_prefix] = MmapedDict(filename)
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/mmap_dict.py", line 61, in __init__
    self._f = open(filename, 'rb' if read_mode else 'a+b')
FileNotFoundError: [Errno 2] No such file or directory: '/deploy/prometheus/histogram_20.db'
[2021-12-16 23:30:38 +0000] [20] [INFO] Worker exiting (pid: 20)
[2021-12-16 23:30:38 +0000] [1] [WARNING] Worker with pid 20 was terminated due to signal 15
[2021-12-16 23:30:38 +0000] [1] [WARNING] Worker with pid 31 was terminated due to signal 15
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 540, in reap_workers
    self.cfg.child_exit(self, worker)
  File "/app/docker/gunicorn_config.py", line 6, in child_exit
    prometheus_client.multiprocess.mark_process_dead(worker.pid)
  File "/opt/venv/lib/python3.8/site-packages/prometheus_client/multiprocess.py", line 161, in mark_process_dead
    for f in glob.glob(os.path.join(path, 'gauge_livesum_{0}.db'.format(pid))):
  File "/usr/local/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/local/lib/python3.8/glob.py", line 34, in iglob
    sys.audit("glob.glob", pathname, recursive)
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by bjoernenders** [comment]
The main issue is the non-root deployment of the container, because the current dir for prometheus is only writable by root. One way the container could be configured is that you need to provide the prometheus dir as env variable. And if you don't, it doesn't do metrics.
