### ISSUE TITLE
change in CLI?

### ISSUE THREAD

**Issue by martindurant** [bluesky/tiled#178]
Tiled is used in testing by Intake. [Recently](https://github.com/intake/intake/runs/5392453814?check_suite_focus=true) our only tiled-based test started to fail. The command that is used to launch a test tiled server is
```
tiled serve pyobject --public tiled.examples.generated:tree
```
and I can confirm that with the latest release, 0.1.0a56, this fails with the following:
```
Traceback (most recent call last):
  File "/Users/mdurant/conda/envs/py38/bin/tiled", line 8, in <module>
    sys.exit(main())
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/tiled/commandline/main.py", line 416, in serve_pyobject
    from ..server.app import build_app, print_admin_api_key_if_generated
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/tiled/server/app.py", line 20, in <module>
    from tiled.database.core import purge_expired
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/tiled/database/core.py", line 13, in <module>
    from .orm import APIKey, Identity, Principal, Role, Session
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/tiled/database/orm.py", line 19, in <module>
    from ..server.schemas import PrincipalType
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/site-packages/tiled/server/schemas.py", line 207, in <module>
    class Identity(pydantic.BaseModel, orm_mode=True):
  File "pydantic/main.py", line 324, in pydantic.main.ModelMetaclass.__new__
  File "/Users/mdurant/conda/envs/py38/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: __init_subclass__() takes no keyword arguments
```

Perhaps the command to make tiled go has changed?

**Comment by danielballan** [comment]
No, no changes there. What version of pydantic is this?

**Comment by martindurant** [comment]
pydantic 1.9.0? 
https://github.com/intake/intake/runs/5392453814?check_suite_focus=true#step:3:2223

**Comment by danielballan** [comment]
It looks to me like it won't even _import_ for you but I cannot reproduce on any recent version of pydantic.

What does this do?

```py
import tiled.server.schemas
```

and this?

```py
import pydantic

class Test(pydantic.BaseModel, orm_mode=True):
    ...
```

**Comment by danielballan** [comment]
Oh, of course, you may not be able to reproduce locally either.

**Comment by martindurant** [comment]
Both those things say
```
TypeError: __init_subclass__() takes no keyword arguments
```
I'm not certain the CI error is the same, except that the tiled server just doesn't come up there.

**Comment by danielballan** [comment]
For me both things work fine:

```
$ python -V
Python 3.9.1
```

```py
>>> import tiled.server.schemas
>>> tiled.__version__
'0.1.0a56'
>>> import pydantic
>>> pydantic.__version__
'1.9.0'
>>> class Test(pydantic.BaseModel, orm_mode=True):
       ...
... 
```

Let's hone in on that.

**Comment by danielballan** [comment]
(Also, sorry for breaking your build and thanks for the report! :-) )

**Comment by martindurant** [comment]
Sounds like it wasn't you :)  I'll look again tomorrow and figure out what version of what is problematic.

**Comment by dylanmcreynolds** [comment]
This pydantic issue looks like the culprit: https://github.com/samuelcolvin/pydantic/issues/2522.  Fixed in May, 2021, not sure when it was released.

**Comment by martindurant** [comment]
Perhaps we should be sure to install tiled's deps from conda before pip-install tiled itself?  There was a 1.8.2 release of pydantic immediately after that PR, and then the single 1.9.0 release since.

**Comment by danielballan** [comment]
It's probably about time to start making conda packages for Tiled, which I guess will help.

I tested each version with 

```py
class Test(pydantic.BaseModel, orm_mode=True):
       ...
```

and found that the problem was introduced in `1.7` and resolved in `1.8`. (Pydantic versioning goes `1.7`, `1.7.1`, ..., `1.8`, `1.8.1`, ....) I will ban `1.7` and `1.7.*` in tiled's requirements file; that may do the trick.

**Comment by danielballan** [comment]
FastAPI bans that at well, but pip doesn't yet traverse that deeply. Because Tiled has it as a direct dependency, FastAPI's pins are not respected.

https://github.com/tiangolo/fastapi/blob/440d2d2d1a72867b3f38b5c7359e021cccbfea8b/pyproject.toml#L39

**Comment by martindurant** [comment]
I got an environment for Intake that works, so closing this. Thanks for the investigation.
