### ISSUE TITLE
Pip install doesn't install dependencies

### ISSUE THREAD

**Issue by J-avery32** [bluesky/tiled#247]
I apologize if this is a mistake on my part, but when I run `pip install tiled` on my machine and then run: `tiled serve pyobject --public tiled.examples.generated:tree` I get this error:
```
Traceback (most recent call last):
  File "/home/j/programming/work/tiled_als/venv/bin/tiled", line 5, in <module>
    from tiled.commandline.main import main
  File "/home/j/programming/work/tiled_als/venv/lib/python3.8/site-packages/tiled/commandline/main.py", line 4, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
```

**Comment by danielballan** [comment]
Thanks again @J-avery32 for this report. I have proposed a change that would produce a better error message with clear instructions in this situation. Feedback on that is welcome.

https://github.com/bluesky/tiled/pull/253

**Comment by J-avery32** [comment]
Ah thank you for the response.
