### ISSUE TITLE
"No response returned" in server logs

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#260]
We are seeing intermittent errors like this when the user is connecting from a hand-made client running in Igor. I do not know if this can be reproduced from other clients.

The discussion here seems relevant: https://stackoverflow.com/questions/71222144/runtimeerror-no-response-returned-in-fastapi-when-refresh-request

```
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: [2022-07-21 11:16:01 -0400] [4001364] [ERROR] Exception in ASGI application
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: Traceback (most recent call last):
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/anyio/streams/memory.py", line 94, in receive
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     return self.receive_nowait()
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     raise WouldBlock
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: anyio.WouldBlock
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: During handling of the above exception, another exception occurred:
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: Traceback (most recent call last):
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 43, in call_next
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     message = await recv_stream.receive()
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/anyio/streams/memory.py", line 114, in receive
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     raise EndOfStream
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: anyio.EndOfStream
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: During handling of the above exception, another exception occurred:
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: Traceback (most recent call last):
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     result = await app(self.scope, self.receive, self.send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     return await self.app(scope, receive, send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     await super().__call__(scope, receive, send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/applications.py", line 124, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     await self.middleware_stack(scope, receive, send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     raise exc
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     await self.app(scope, receive, _send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     await self.app(scope, receive, send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 68, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     response = await self.dispatch_func(request, call_next)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/tiled/server/app.py", line 525, in set_cookies
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     response = await call_next(request)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 46, in call_next
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     raise app_exc
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 36, in coro
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     await self.app(scope, request.receive, send_stream.send)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 68, in __call__
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     response = await self.dispatch_func(request, call_next)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/tiled/server/app.py", line 509, in double_submit_cookie_csrf_protection
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     response = await call_next(request)
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:   File "/srv/tiled/venv/lib64/python3.8/site-packages/starlette/middleware/base.py", line 47, in call_next
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]:     raise RuntimeError("No response returned.")
Jul 21 11:16:01 tiled9.nsls2.bnl.gov gunicorn[4001342]: RuntimeError: No response returned.
Jul 21 11:16:02 tiled9.nsls2.bnl.gov gunicorn[4001342]: [2022-07-21 11:16:02 -0400] [4001356] [ERROR] Exception in ASGI application
```

**Comment by danielballan** [comment]
The Igor client was setting aggressively low timeouts (1 or 2 seconds) and that was causing this issue. The Igor client author reports that extending the timeouts resolved the issue.
