### ISSUE TITLE
DirectoryAdapter crash with similar file names

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#336]
To reproduce:

1. create a /tmp/tiled directory that has:

```
(tiled) ➜  tiled git:(main) tree /tmp/tiled
/tmp/tiled
├── file.foo1
└── file.foo2
```

2. run `tiled serve directory /tmp/tiled`

3. Observe that tiled crashes with the following:
```
(tiled) ➜  tiled git:(main) tiled serve directory /tmp/tiled
/opt/miniconda3/envs/tiled/lib/python3.10/site-packages/tiled/adapters/files.py:707: UserWarning: The file at /tmp/tiled/file.foo2 has some type that is not recognized. The file will be skipped. Pass in a mimetype for this file extension via the parameter DirectoryAdapter.from_directory(..., mimetypes_by_file_ext={...}) or a function for determining the mimetype based the full filepath DirectoryAdapter.from_directory(..., mimetype_detection_hook=func).
  warnings.warn(msg)
/opt/miniconda3/envs/tiled/lib/python3.10/site-packages/tiled/adapters/files.py:323: UserWarning: The file file.foo1 maps to the key 'file'. which collides with the file(s) ['file.foo2']. All files that map to this key will be ignored until the collision is resolved. To resolve this do one of the following: (1) Use the full, unique filename as the key, via the commandline flag --keep-ext or the configurable argument key_from_filename: 'tiled.adapters.files:identity'  # Use full filename as key (2) Remove or rename one of the files. (3) Use a custom key_from_filename that generates unique keys for this case.
  warnings.warn(
Traceback (most recent call last):

  File "/opt/miniconda3/envs/tiled/bin/tiled", line 8, in <module>
    sys.exit(main())

  File "/opt/miniconda3/envs/tiled/lib/python3.10/site-packages/tiled/commandline/main.py", line 491, in serve_directory
    tree = DirectoryAdapter.from_directory(directory, **tree_kwargs)

  File "/opt/miniconda3/envs/tiled/lib/python3.10/site-packages/tiled/adapters/files.py", line 330, in from_directory
    index[parts].remove(key)

  File "/opt/miniconda3/envs/tiled/lib/python3.10/site-packages/tiled/utils.py", line 232, in remove
    del self.__mapping[key]

KeyError: 'file'
```

**Comment by dylanmcreynolds** [comment]
Since neither of the two files actually registered, the call to delete from the map fails.

**Comment by danielballan** [comment]
Makes sense. I think a simple fix will work here: change that `del  self.__mapping[key]` to `self.__mapping.pop(key, None)`.
