### ISSUE TITLE
Investigate build issue involving cython and thriftpy in container build

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#526]
Cython recently release 3.0.0. In the container build GHA, I have pinned cython to `<3` to work around the error below. Perhaps upstream will fix; we should try un-pinning soon.

```
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Compiling thriftpy2/transport/cybase.pyx because it changed.
      [1/1] Cythonizing thriftpy2/transport/cybase.pyx
      /opt/venv/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-l_vvkf17/thriftpy2_dbce685136344ce8a8f1fa2e7857ec70/thriftpy2/transport/cybase.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef int grow(self, int min_size):
              if min_size <= self.buf_size:
                  return 0
      
              cdef int multiples = min_size / self.buf_size
                                            ^
      ------------------------------------------------------------
      
      thriftpy2/transport/cybase.pyx:90:38: Cannot assign type 'double' to 'int'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l_vvkf17/thriftpy2_dbce685136344ce8a8f1fa2e7857ec70/setup.py", line 61, in <module>
          cythonize("thriftpy2/transport/cybase.pyx")
        File "/opt/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/opt/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: thriftpy2/transport/cybase.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c TILED_BUILD_SKIP_UI=1 pip install '.[server]'' returned a non-zero code: 1

Error: Process completed with exit code 1.
```

**Comment by danielballan** [comment]
xref https://github.com/Thriftpy/thriftpy2/issues/218
