### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#566]
I've got file directories with multiple suffixes, such that `something.txt`, `something.md`, and `something.dat` coexist.  That means now to use the `tiled catalog register --keep-ext` option, like this:

```
$ tiled catalog register -vvv --keep-ext dev_sampler.sql ./dev_sampler
Traceback (most recent call last):

  File "/home/beams/JEMIAN/.conda/envs/tiled/bin/tiled", line 8, in <module>
    sys.exit(main())
             ^^^^^^

  File "/home/beams/JEMIAN/.conda/envs/tiled/lib/python3.11/site-packages/tiled/commandline/_catalog.py", line 155, in register
    from ..adapters.files import identity

  File "/home/beams/JEMIAN/.conda/envs/tiled/lib/python3.11/site-packages/tiled/adapters/files.py", line 1, in <module>
    raise Exception(

Exception: The way that tiled serves files has changed.

See documentation section "Serve a Directory of Files".
```

**Comment by prjemian** [comment]
Looks like this line has not kept up with the code updates: https://github.com/bluesky/tiled/blob/26c4ecf89c10ce97cf2b9c7339510f18e43eb52a/tiled/commandline/_catalog.py#L155

since that file is one big fat exception raiser: https://github.com/bluesky/tiled/blob/26c4ecf89c10ce97cf2b9c7339510f18e43eb52a/tiled/adapters/files.py#L1-L6

**Comment by prjemian** [comment]
Local change to that line 155 above works:

```py
        from ..catalog.register import identity
```
