### ISSUE TITLE
Reading Awkward Arrays requires URLs that are too long

### ISSUE THREAD

**Issue by jpivarski** [bluesky/tiled#574]
I don't remember where I mentioned this[^1], but one thing that I'm using this for is to collect metadata for a set of ROOT files, which can then be accessed more quickly (like [kerchunk](https://fsspec.github.io/kerchunk/), but ROOT metadata is big enough that it can't be JSON).

I started this project (https://github.com/jpivarski/tiled-uproot), using Awkward Arrays in Tiled for the metadata. For each PB of ROOT data, I estimate about 10 TB of metadata will be needed in the database. (User derived quantities will be smaller, and it will be nice to be able to access the original ROOT data and derived quantities with the same tools.)

I ran this on 3 typical files, resulting in an Awkward Array whose Form JSON is 786 kB, has 5639 buffers containing a total of 42 MB. With more files, the size of the Form and number of buffers will not increase, but the total amount of data in the buffers will increase.

I had no trouble writing this Awkward Array in Tiled, and I could read back small slices of it. However, some queries, the ones addressing the larger parts of the array, raised this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/tiled/client/awkward.py", line 55, in __getitem__
    return self.read(slice=slice)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/tiled/client/awkward.py", line 39, in read
    self.context.http_client.get(
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_client.py", line 801, in request
    request = self.build_request(
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_client.py", line 358, in build_request
    return Request(
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_models.py", line 330, in __init__
    self.url = self.url.copy_merge_params(params=params)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_urls.py", line 360, in copy_merge_params
    return self.copy_with(params=self.params.merge(params))
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_urls.py", line 348, in copy_with
    return URL(self, **kwargs)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = url._uri_reference.copy_with(**kwargs)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_urlparse.py", line 134, in copy_with
    return urlparse("", **defaults)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/httpx/_urlparse.py", line 200, in urlparse
    raise InvalidURL(f"URL component '{key}' too long")
```

Given this scale of Form JSON, maybe the URL-based query can be replaced by POST data?

[^1]: Finally found it: it was a private email with subject line "Using Tiled as a kerchunk-like database for ROOT files". I copied it here: https://github.com/jpivarski/tiled-uproot/discussions/1.

**Comment by danielballan** [comment]
Yes, I think that make sense.

I once read an argument that every `GET` route should also support `POST`, for this reason. While I wouldn't take that argument so far, this is a case where it applies: we should support `GET` for ease of use in simple cases (typing into `curl ...`) and `POST` for the general case where the concatenated names of the form keys may grow large.

I am very interested in this use case; I replied in the linked Discussion.
