### ISSUE TITLE
docker issue with postgres: psycopg2

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#615]
Using the docker container of tiled, and I have configured it to talk to postgres:

```
database:
  uri: postgresql://username:password@postgres/tiled
```

On startup, it fails, missing the postgres driver module. Is there any well known solution other than "build and maintain your own image that installs postgres code?

```
Using configuration from /config/main
Traceback (most recent call last):

  File "/opt/venv/bin/tiled", line 8, in <module>
    sys.exit(main())
             ^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/tiled/commandline/_serve.py", line 563, in serve_config
    web_app = build_app_from_config(
              ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/tiled/server/app.py", line 839, in build_app_from_config
    kwargs = construct_build_app_kwargs(config, source_filepath=source_filepath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/tiled/config.py", line 142, in construct_build_app_kwargs
    tree = obj(**args)
           ^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/tiled/catalog/adapter.py", line 1060, in from_uri
    engine = create_async_engine(uri, echo=echo, json_serializer=json_serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 117, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<string>", line 2, in create_engine

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2

ModuleNotFoundError: No module named 'psycopg2'

```

**Comment by dylanmcreynolds** [comment]
Duh. Many thanks.
